
theme = "monokai_tasty"

[editor]
color-modes = true
cursorline = true
completion-trigger-len = 0
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
C-s = ":w"
J = "goto_next_paragraph"
K = "goto_prev_paragraph"
C-j = "join_selections"
C-k = "keep_selections"

[keys.insert]
k = { j = "normal_mode" }
C-s = ":w"
