# manual scala settings to workaround https://github.com/helix-editor/helix/issues/3823
[[language]]
name = "scala"
scope = "source.scala"
roots = ["build.sbt", "pom.xml"]
file-types = ["scala", "sbt"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "metals" }
config = {metals.ammoniteJvmProperties = ["-Xmx1G"]}
